### ISSUE TITLE
Dragging sometimes starts at wrong location

### ISSUE THREAD

**Issue by jordantomax** [quarterto-archive/Elessar#100]
video of bug: https://www.dropbox.com/s/zy2qr4drwqhj8ji/elessar-drag-starting-location.mov?dl=0

my code: 

```
        var rangeBar = new RangeBar({
            min: moment().startOf('day').format('LLLL'),
            max: moment().endOf('day').format('LLLL'),
            valueFormat: function(ts) {
                return moment(ts).format('LLLL');
            },
            valueParse: function(date) {
                return moment(date).valueOf();
            },
            label: function(a){
                return moment(a[1]).from(a[0], true);
            },
            snap: 1000 * 60 * 60,
            minSize: 1000 * 60 * 60,
            barClass: 'progress',
            rangeClass: 'bar',
            allowDelete: true,
            handleClick: $scope.activateRange
        });

        $(el).append(rangeBar.$el)
            .on('change', function(values, range) {
                console.log(range)
                $scope.values = range;
            })
            .on('changing', function(values, range) {
                console.log(range)
                $scope.values = range;
            })
            ;
```

Any ideas why this might be happening?

**Comment by jordantomax** [comment]
This is actually happening after I create the range as well. So if I create a range, then click to expand it, it suddenly shifts to the left a number of spaces.

**Comment by quarterto** [comment]
Ah. Ranges use `clientX/Y` in the mouse events, which are relative to the screen, not the page. When you scroll, it causes an offset. I'll look into using `pageX/Y` (I seem to recall some reason it wouldn't work, but I don't remember now).

**Comment by jordantomax** [comment]
Hmm, seems like if it affected Y position, then it wouldn't work at all while over the rangebar, don't you think? It seems only be affecting X, and it would be a little strange if the X position was being affected by scroll, which only happens in the Y direction.

**Comment by quarterto** [comment]
The page in your video appears to be scrolled horizontally. I mentioned Y because Elessar also supports vertical scrollbars, and we've had a similar problem with those (#77).

**Comment by jordantomax** [comment]
Ah, so it is. Interesting, that makes sense. I'll look into that.

**Comment by jordantomax** [comment]
I can confirm that the problem only happens when there is horizontal scrolling on the page.
