### ISSUE TITLE
How to add a mouse click handler to Ranges?

### ISSUE THREAD

**Issue by brunofin** [quarterto-archive/Elessar#103]
Hello,

Firstly, I would like to say that this library is awesomely useful and thank you for making it open-source! :)

I'm struggling since yesterday with a simple problem, I want to add a custom handle to when the user clicks on a range (not on the rangebar itself), but I can't find how. Could I get a help, please? Thanks!

**Comment by quarterto** [comment]
There are hacky ways to do it with `options.label` or the `addRange` event, but both are brittle:

  * label is called every time a range changes, so you need to make sure you only add the handler once
  * addRange is only fired when a range is added by clicking on the bar, not for ranges added implicitly by `val`
  * there's no way to clean up after either of them, so you'll leak memory

I will eventually add proper "range added/removed" hooks. Currently this project is a bit of a mess and makes me sad every time I try to work on it. At some point it needs totally rewriting. These hooks will probably come as part of the rewrite.

**Comment by brunofin** [comment]
@quarterto Thanks for your comment! I'm working on a wrapper for AngularJS, the solution I came up with was to loop through every `range` in a rangebar and add the `.on('click', ...)` event listener, while this works it still doesn't overwrite the middle click, but it's already something :)

If you're interested in taking a look, here's the code:

https://github.com/brunofin/angular-elessar/blob/0.9.1/angular-elessar.js#L183
