### ISSUE TITLE
Range scale is inconsistent

### ISSUE THREAD

**Issue by jordantomax** [quarterto-archive/Elessar#104]
when calling .val(), you get back set of ranges that take into account the scale of the rangebar, through mapping the array:

```
return range.val().map($.proxy(self.normalise, self));
```

However, in almost all other places, including listening to "change", you are returned an unnormalized range. For me, it would always be better to get back a normalized range.

**Comment by quarterto** [comment]
Related: #89. Basically the only place you get a normalised value from is `val`. Don't really know what to do about this; it's much easier to pass around "abnormalised" values internally, and for things like `.on` it's not really a thing to pass flags.

**Comment by jordantomax** [comment]
I understand, that makes sense. Possibly attach them both as attributes to each range? Like normalizedRange, and range? I'm having to rewrite your normalize code inside of my app to make the conversion. It would be nice if everywhere I had access to a range, I also had access to the normalized values.
