### ISSUE TITLE
has.call(event, prop) returns false

### ISSUE THREAD

**Issue by brunofin** [quarterto-archive/Elessar#112]
I'm having trouble with Elessar. All of a sudden, the bars aren't moving anymore. We're using version `1.8.4`.

I've debugged until I found this https://github.com/quarterto/Elessar/blob/master/lib/eventprop.js

This code always returns `0`. I changed it to simply `return event[prop];` with no verifications, and my rangebars started to work again.

I would create a PR to change this line but I'm not sure how it would affect the rest of the system or other users. So, is there any reason why this line is always returning `0` for me? Something I can fix in my code?

**Comment by quarterto** [comment]
Changing it to `event[prop]` would false-negative if it's zero (that function is mostly used for `clientX`/`clientY`). `typeof event[prop] !== 'undefined'` would be better, but I'm intrigued why `hasOwnProperty` is returning `false`. What browser are you testing in?

**Comment by brunofin** [comment]
I'm mainly testing in Chrome 52 on Fedora 24, but I have confirmed this behavior in Firefox and IE (on W10) as well, that's why I'm tending to believe something is wrong with our code, but we haven't changed anything related to where the Rangebars are used in a very long time. Is it possible that CSS could be playing a role in this problem?

**Comment by brunofin** [comment]
I created a PR replacing `Object.hasOwnProperty` by the `in` operator in that file. I probably should have checked if `hasOwnProperty` is used somewhere else, but honestly that's the only place where it's breaking, so maybe it's not necessary and even out of the scope of this issue.

Local tests were OK but the ones triggered by the PR failed, it seems there are no credentials, I'm not sure if I should have provided some or something else is wrong though.
