### ISSUE TITLE
Ability to toggle `readonly`?

### ISSUE THREAD

**Issue by bensaufley** [quarterto-archive/Elessar#88]
I know documentation's one of the big "next steps" here, so maybe I'm just missing it, but I can't figure out how to toggle `readonly` without deleting and rebuilding a range, which isn't really practical.

**Comment by quarterto** [comment]
Readonly can [take a function](https://github.com/quarterto/Elessar/blob/e7b8563a8f9112e22cdf3494dd84907c8c0c78a7/lib/rangebar.js#L207) that returns a boolean. However, changing the readonly state will only affect any ranges created afterwards. Any existing ranges in the bar won't get the `elessar-readonly` class and keep their event handlers.

**Comment by bensaufley** [comment]
For my purposes I've got a parent div that toggles `.editing` anyway so I'm just creating a pseudoelement and placing it over the range. But as the range is likely to be used as an input among other inputs by others too, it would be great to be able to toggle that like one can toggle `disabled`

**Comment by quarterto** [comment]
Range could be refactored to check `readonly` in the event handlers rather than at construction. I don't really have time for that right now but a pull request is always welcome :)
