### ISSUE TITLE
Adding interval at android 4.4.2

### ISSUE THREAD

**Issue by acheshkov** [quarterto-archive/Elessar#92]
Hi, 

adding interval does not work at android 4.4.2.

**Comment by quarterto** [comment]
Thanks for the report @acheshkov. What exactly are you trying in order to add the range, and what happens when you try?

Adding ranges on touch screens is a little tricky. You have to tap once in an empty space on the bar, then tap the grey `+` range when it appears. Is this what you're trying?

**Comment by acheshkov** [comment]
i tap once and "phantom" bar appears. but the second tab do nothing. 
sometimes it works  and allows to add one interval and no one more.

**Comment by quarterto** [comment]
Ok, thanks. Is this with Chrome or Android Browser?

**Comment by acheshkov** [comment]
yes, it's chrome
