### ISSUE TITLE
Change event being called multiple times on change

### ISSUE THREAD

**Issue by jordantomax** [quarterto-archive/Elessar#99]
Video of the problem I'm experiencing: https://www.dropbox.com/s/673mlxgnta9u49a/elessar-on-change-recording-480p.mov?dl=0

My code is as follows:

```
        var rangeBar = new RangeBar({
            min: moment().startOf('day').format('LLLL'),
            max: moment().endOf('day').format('LLLL'),
            valueFormat: function(ts) {
                return moment(ts).format('LLLL');
            },
            valueParse: function(date) {
                return moment(date).valueOf();
            },
            label: function(a){
                return moment(a[1]).from(a[0], true);
            },
            snap: 1000 * 60 * 60,
            minSize: 1000 * 60 * 60,
            barClass: 'progress',
            rangeClass: 'bar'
        });

        $(el).append(rangeBar.$el)
            .on('change', function(ev, ranges) {
                console.log(ranges)
            })
            .on('changing', function(ev, ranges) {
            })
            ;
```

I'm also running into some weirdness when adding a new range. Sometimes it waits for another click to decide the endpoint of the range, other times, it just creates the range with the minimum size. Any idea what could be causing these problems? Figured I'd ask before digging in myself. 

Thanks in advance!

**Comment by quarterto** [comment]
I can confirm this bug. It's only happening when you click without dragging. We had similar problems before (#61) which was caused by a leaking `mouseup` event handler, which could possibly be happening here. We also had #60, which is about *no* events being fired in this case. Looks like we've gone too far the other way :wink:

As for the other issue, it's possible you're actually triggering the `mouseup` *outside* of the phantom range, which would then just trigger the dragging behaviour on mouse move.

**Comment by quarterto** [comment]
Aha, [this event](https://github.com/quarterto/Elessar/blob/1.8.4/lib/rangebar.js#L232) probably needs namespacing.

**Comment by jordantomax** [comment]
Namespacing does appear to work, not sure if there's a better solution as I'm definitely not as familiar with the code as you are :P Are there docs to work with the src files? I've just added it to the dist right now, but it would be nice to be able to submit a proper pull request, especially for future issues.

**Comment by jordantomax** [comment]
scratch that, it's still broken!

**Comment by jordantomax** [comment]
I can throttle the events outside of the plugin, but I would definitely be very interested in a proper solution.

**Comment by jcaverhagen** [comment]
Is this bug solved yet? or does someone know a good solution?

Thanks in advance.

**Comment by brunofin** [comment]
I'm using this workaround:

```javascript
var timeout = null;
var onChangeFn = function(event, values, range) {
              // workaround for a known bug where many events are triggered when just one should be
              // https://github.com/quarterto/Elessar/issues/99
              clearTimeout(timeout);
              timeout = setTimeout(function() {
                // Do what you need to do here
              }, 10);
          }
rangebar.on('change', onChangeFn);
```
